### ISSUE TITLE
2020.11.12 - 업무 지정

### ISSUE THREAD

**Issue by oMFDOo** [tomorrow9913/oop-project#1]
**이번 주 업무**
1. 승민, 주용 - 클래스 도큐먼트 작성
  : 클래스 역할과 클래스에 들어있는 변수 및 타입 설명 글 작성
※ 파일명은 클래스타입정리-YYYY.MM.DD

2. 민규, 진주 - 깃 레포지터리 생성(완)
 : 레포 생성 및 어트리뷰트추가, 태그 정리

3. 유정, 원준 - 입출금 내역 클래스 작성(완)
 : 협의 토대로 클래스 이름 정의, 변수 정의 
※ 함수나 그 외의 것은 제외

+파일 분리에 따른 업무추가 : 
민규 : 각 파일 설명을 클래스 도큐먼트에 추가

**Comment by uzhjd** [comment]
3번 완료 했습니다!!

**Comment by tomorrow9913** [comment]
각 파일 분리와 관련된 문서는 README 파일과 각 클래스 도큐먼트로 업로드 되었음.
아직 작성되지 않은 문서에 대해서는 도큐먼트 폴더에 올라올 예정. 
파일 명은 이후 문서 이력 관리를 위해 제목은 변경함

https://github.com/tomorrow9913/oop-project

+ md 대신 워드 파일로 도큐먼트 작성 했을 경우 메인에서 컨플릭트 발생시 해결 방안 필요함.
+ 일반 txt로 작성할 거면...  md도 나쁘지 않은거 같은데....
+ 해당 내용에 대해서 답글 바람. @oMFDOo
