### ISSUE TITLE
BUG : 음수 금액 활용가능(4개)

### ISSUE THREAD

**Issue by lsm8424** [tomorrow9913/oop-project#11]
** 버그 설명 **
버그가 무엇인지 명확하고 간결하게 설명합니다.
- [계좌 생성시 음수금액으로 생성이 가능합니다. ] 
- [입금시 음수 금액으로 입금이 가능합니다.]
- [이체시 음수 금액으로 이체가 가능합니다.]
- [출금시 음수 금액으로 출금이 가능합니다.]

** 재현 방법 **
동작을 재현하는 단계 :
1. '계좌 개설, 입금. 이체, 출금'로 이동
2. 금액 입력란에 음수를 기재
3. 문제없이 진행됩니다.

** 예상 동작 **
- 음수금액 입력시 잘못된 입력 처리
- 

** 스크린 샷 **
해당되는 경우 문제를 설명하는 데 도움이되는 스크린 샷을 추가합니다.

** 추가 내용 **
추가 할 내용

**Comment by tomorrow9913** [comment]
해결완료
