### ISSUE TITLE
BUG : 비밀번호 지정 가능 범위(1개)

### ISSUE THREAD

**Issue by lsm8424** [tomorrow9913/oop-project#12]
** 버그 설명 **
버그가 무엇인지 명확하고 간결하게 설명합니다.
- [비밀번호로 백스페이스 및 숫자 이외의 다른 입력도 가능합니다] 

** 재현 방법 **
동작을 재현하는 단계 :
1. '계좌 개설'로 이동
2. 개설중 비밀번호 입력란에 여러 키 입력
3. 오류가 발생하지 않음

** 예상 동작 **
- 비밀번호로 입력가능한 범위를 지정해주거나 그대로 두면 될것 같습니다.
- 

** 스크린 샷 **
해당되는 경우 문제를 설명하는 데 도움이되는 스크린 샷을 추가합니다.

** 추가 내용 **
추가 할 내용

**Comment by tomorrow9913** [comment]
버그가 아니라 기능이에요
