### ISSUE TITLE
BUG : 업무 선택 입력에서 숫자이외 문자 입력시 화면 깜빡임&먹통 (1개)

### ISSUE THREAD

**Issue by lsm8424** [tomorrow9913/oop-project#13]
** 버그 설명 **
버그가 무엇인지 명확하고 간결하게 설명합니다.
- [잘못된 숫자시 재 입력 가능하지만 잘못된 문자 입력시 재 입력이 불가능합니다 ] 

** 재현 방법 **
동작을 재현하는 단계 :
1. 업무 선택 기능에 숫자를 제외한 문자 입력
2. 오류 발생(화면 깜빡임& 먹통)

** 예상 동작 **
-  재 입력가능하게 처리
- 

** 스크린 샷 **
해당되는 경우 문제를 설명하는 데 도움이되는 스크린 샷을 추가합니다.

** 추가 내용 **
추가 할 내용

**Comment by tomorrow9913** [comment]
처리 완료
