### ISSUE TITLE
BUG : 업무 처리후 "키 입력시 메인 화면으로 돌아갑니다..." 관련 오류 (2개)

### ISSUE THREAD

**Issue by lsm8424** [tomorrow9913/oop-project#14]
** 버그 설명 **
버그가 무엇인지 명확하고 간결하게 설명합니다.
- [키를 입력하시오 뒤에 숫자를 입력시 메인화면으로 돌아왔을떄 잘못된 업무를 선택하였다고 경고 알림이 뜸]
- [키를 입력하시오 뒤에 문자를 입력시 메인화면으로 돌아왔을떄 잘못된 업무를 선택하였다고 경고 알림이 뜨고 화면이 깜빡이며 프로그램이 먹통 ] 

** 재현 방법 **
동작을 재현하는 단계 :
1. 아무 업무 이후 다시 메인으로 돌아가기 위해 뜨는 '키 입력시 메인 화면으로 돌아갑니다...' 뒤에 문자나 숫자 입력시 각 종류별로 오류 발생

** 예상 동작 **
- 아무런 문제 없이 메인으로 정상 복귀
- 

** 스크린 샷 **
해당되는 경우 문제를 설명하는 데 도움이되는 스크린 샷을 추가합니다.

** 추가 내용 **
추가 할 내용

**Comment by tomorrow9913** [comment]
해당 이슈는 버퍼 초기화 안되어서 그런것으로 추정

**Comment by oMFDOo** [comment]
엔터키 입력시 종료로 문구 수정함
