### ISSUE TITLE
BUG : 출금시 입력이 숫자가 아닐 경우 (1개)

### ISSUE THREAD

**Issue by ju1645** [tomorrow9913/oop-project#16]
** 버그 설명 **
버그가 무엇인지 명확하고 간결하게 설명합니다.
- [출금할때 출금 숫자로 숫자가 아닌걸 입력하면 깜박임 오류]
- [ ] 

** 재현 방법 **
동작을 재현하는 단계 :
1. '출금'으로 이동
2. '숫자외 다른 문자 입력'
3. 오류 발생

** 예상 동작 **
- 경고 숫자가 아닙니다
-  이전 화면으로 이동

** 스크린 샷 **

** 추가 내용 **
추가 할 내용

**Comment by tomorrow9913** [comment]
해결완료
