### ISSUE TITLE
BUG : 버그의 내용 (1개)

### ISSUE THREAD

**Issue by uzhjd** [tomorrow9913/oop-project#17]
** 버그 설명 **
버그가 무엇인지 명확하고 간결하게 설명합니다.
- [x] 입금에서 입금액을 문자로 입력하면 화면이 난리나요!!

** 재현 방법 **
동작을 재현하는 단계 :
1. 메뉴에서 입금으로 이동
2. 생성된 계좌에서 입금을 클릭하십시오.
3. 입금액을 문자로 입력하십시오.
4. 오류 발생

** 예상 동작 **
-  올바른 입금액을 입력해주십시오!

** 스크린 샷 **
카톡내용 확인하십쇼

** 추가 내용 **
추가 할 내용

**Comment by tomorrow9913** [comment]
제목 수정해주시면 나중에 작업할때 편할것 같읍니다

**Comment by tomorrow9913** [comment]
해결 완료
