### ISSUE TITLE
BUG : 송금 금액 문자로 입력시 오류 발생 (1개)

### ISSUE THREAD

**Issue by uzhjd** [tomorrow9913/oop-project#18]
** 버그 설명 **
버그가 무엇인지 명확하고 간결하게 설명합니다.
- [x] 송금금액을 문자로 입력하면 오류가 납니다.

** 재현 방법 **
동작을 재현하는 단계 :
1. 메뉴에서 송금으로 이동
2. 송금금액을 문자로 입력하십시오.
4. 오류 발생

** 예상 동작 **
- 올바른 송금금액을 입력하시오

** 스크린 샷 **
카톡화면 확인바랍니다.

** 추가 내용 **
추가 할 내용

**Comment by tomorrow9913** [comment]
해결완료
