### ISSUE TITLE
BUG : 생성할 계좌 종류 선택시 음수로 입력하면 메뉴가 한번 더 나옵니다.(1개)

### ISSUE THREAD

**Issue by uzhjd** [tomorrow9913/oop-project#20]
** 버그 설명 **
버그가 무엇인지 명확하고 간결하게 설명합니다.
- [x] 계좌 종류를 선택할 때, 1, 2번이 아닌 음수로 입력하면 화면이 클리어 되지 않고 메뉴창이 나옵니다

** 재현 방법 **
동작을 재현하는 단계 :
1. 계좌 생성으로 이동
2. 1, 2가 아닌 음수로 선택하십시오.
3. 오류 발생

** 예상 동작 **
- 올바른 번호를 선택하십시오.

** 스크린 샷 **
카톡확인 바랍니다.

** 추가 내용 **
추가 할 내용

**Comment by tomorrow9913** [comment]
8번에 해당 내용 추가하여 업로드하였음
